### ISSUE TITLE
头部切换年月的箭头图标无法显示，

### ISSUE THREAD

**Issue by liuwenhao19960508** [kuan1/kuan-vue-calendar#3]
引入到我的项目中后，头部切换箭头显示不了，但是是存在的，可以点击，只是没有展示，应该是样式的问题吧

**Comment by kuan1** [comment]
> 引入到我的项目中后，头部切换箭头显示不了，但是是存在的，可以点击，只是没有展示，应该是样式的问题吧

打包的时候忘了引入这个css，你可以先手动引入，下个版本我会把css打包进去

```html
   <link
      rel="stylesheet"
      href="//at.alicdn.com/t/font_1230434_v968elyade.css"
    />
```

**Comment by liuwenhao19960508** [comment]
@kuan1 
从左往右的周几显示是周日到周六吗？如果是周一到周日就会提前一天，比如今天8.1，周四，按照周一到周日的话，它是在周五的位置，按照周日到周六的话就是正常的

**Comment by kuan1** [comment]
> @kuan1
> 从左往右的周几显示是周日到周六吗？如果是周一到周日就会提前一天，比如今天8.1，周四，按照周一到周日的话，它是在周五的位置，按照周日到周六的话就是正常的

应该显示星期的，我已经加上了，周日-> 周六显示，多谢提醒 @liuwenhao19960508
